import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/lib";

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: '--font-outfit', 
  display: 'swap', 
})

export const metadata: Metadata = {
  title: "Mindgest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${outfit.style} ${outfit.className} antialiased`}
      >
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
