import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/lib";
import { ModalProvider } from "@/contexts";
import { ThemeProvider } from "@/components/theme-provider";

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-outfit',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Mindgest",
  description: "Generated by create next app",
  icons: {
    icon: "/mindware.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfit.variable} ${outfit.className} antialiased`}
      >
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        themes={["light", "dark", "system"]}
        storageKey="mindware-theme"
        >
        <ModalProvider>
          <ReactQueryProvider>
            {children}
          </ReactQueryProvider>
        </ModalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
